spring:
  datasource:
    url: ${DATABASE_URL:jdbc:mysql://localhost:3306/dev}
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:root}
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate.format_sql: true
  flyway:
    url: ${DATABASE_URL:jdbc:mysql://localhost:3306/dev}
    user: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:root}
    locations: classpath:/db/migration